### ISSUE TITLE
Send button (grey-out)

### ISSUE THREAD

**Issue by zaibatsu777** [IncredibleWeb/Progressive-Web-Chat#20]
Hello,

i have installed the app in my local web-server.
The send button is seemed to be disable? Am i missing a step through the installation or something

**Comment by kevinfarrugia** [comment]
Hi,

This demo is not maintained, it is likely that if you open the console you would see a number of errors. This is because the notification hub we were using is currently disabled.

You will see an error for the following URL:
```
http://progressivewebchat-signalr.localhost/signalr/hubs
```

The send button is enabled once the user manages to connect to the hubs and is connected to the internet.

**Comment by zaibatsu777** [comment]
Hello Kevin,

Thanks for the update.
